### PR TITLE
adds a PR and issue template

### LINKED ISSUE #60: Set up an issue template
In order to make it easy to receive the needed info with bug reports we should set up an issue template.

### PR DESCRIPTION
**Pull request by floriank**
closes #60

see
https://github.com/stevemao/github-issue-templates/blob/master/simple/

I just used the simplest template I could find.

### CODE REVIEW

**Comment by floriank** [comment]
Wait, do i have to setup github actions on my fork for the build to run?

**Comment by paulgoetze** [comment]
> Wait, do i have to setup github actions on my fork for the build to run?

I think so, yes. (See https://github.community/t5/GitHub-Actions/Run-a-GitHub-action-on-pull-request-for-PR-opened-from-a-forked/m-p/31147#M690)

**Comment by floriank** [comment]
I think we actually need to enable the `pull_request` event in the workflow for this repo, as right now it's only on `push`.

**Comment by paulgoetze** [comment]
@floriank Ooh, right. Nice catch! Could you just add it to the elixir.yml here, so we directly see whether it works?

**Pull request merged**
